//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 09:48:34 AM ICT 
//


package th.go.nhso.nnsplims.ws.enpoint.model;

import javax.xml.bind.annotation.XmlRegistry;

import th.go.nhso.nnsplims.jpa.model.Item;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.go.nhso.item_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.go.nhso.item_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindItemByNameRequest }
     * 
     */
    public FindItemByNameRequest createFindItemByNameRequest() {
        return new FindItemByNameRequest();
    }

    /**
     * Create an instance of {@link FindItemByNameResponse }
     * 
     */
    public FindItemByNameResponse createFindItemByNameResponse() {
        return new FindItemByNameResponse();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

}
