//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 09:48:34 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nhso.go.th/item-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package th.go.nhso.nnsplims.ws.enpoint.model;
